export const dashboard =<i className="fa-solid fa-house"></i>
export const transactions = <i className="fa-solid fa-credit-card"></i>
export const categories = <i className="fa-solid fa-tags"></i>
export const accounts = <i className="fa-solid fa-wallet"></i>
export const settings = <i className="fa-solid fa-cog"></i>
export const logout = <i className="fa-solid fa-sign-out"></i>
export const trend = <i className="fa-solid fa-money-bill-trend-up"></i>
export const expenses = <i className="fa-solid fa-money-bill-transfer"></i>
export const money = <i className="fa-solid fa-money-bill"></i>
export const freelance = <i className="fa-solid fa-circle-earth-americas"></i>
export const stocks = <i className="fa-solid fa-arrow-trend-up"></i>
export const bitcoin = <i className="fa-solid fa-bitcoin"></i>
export const piggy = <i className="fa-solid fa-piggy-bank"></i>
export const yt = <i className="fa-solid fa-youtube"></i>
export const card = <i className="fa-solid fa-cc-visa"></i>
export const users = <i className="fa-solid fa-users-between-lines"></i>
export const dollar = <i className="fa-solid fa-dollar-sign"></i>
export const calendar = <i class="fa-solid fa-fire-calendar"></i>
export const down = <i className="fa-solid fa-caret-down"></i>
export const trash = <i className="fa-solid fa-trash"></i>
export const admin = <i className="fa-solid fa-lock"></i>
export const copy = <i className="fa-solid fa-clipboard"></i>
export const githubIcon = <i className="fa-brands fa-github"></i>
export const linked = <i className="fa-brands fa-linkedin"></i>
export const mailIcon = <i className="fa-solid fa-envelope"></i>
export const expand = <i className="fa-solid fa-expand"></i>
export const plus = <i className="fa-solid fa-plus"></i>
export const xmark = <i className="fa-solid fa-xmark"></i>